language: c
dist: trusty
sudo: required

notifications:
  email: false

git:
  submodules: true
  depth: 3

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages: ['python-pip', 'python-yaml']
      before_install:
        - openssl aes-256-cbc
          -K $encrypted_e84e7849f94f_key
          -iv $encrypted_e84e7849f94f_iv
          -in config/travisci_rsa.enc
          -out config/travisci_rsa
          -d
        - chmod 0600 config/travisci_rsa
        - cp config/travisci_rsa ~/.ssh/id_rsa
      before_script:
        - pip install --user git+git://github.com/eddyxu/cpp-coveralls.git
      script:
          - mkdir build && cd build
          - cmake -DCOVERALLS=1 -DCMAKE_BUILD_TYPE=Debug ..
          - cmake --build .
          - cd ../
          - ./build/test

      after_success:
        - coveralls -e build/CMakeFiles/feature_tests.cxx -e build/CMakeFiles/feature_tests.c -e build/CMakeFiles/CompilerIdCXX/CMakeCXXCompilerId.cpp -e build/CMakeFiles/CompilerIdCXX/CMakeCXXCompilerId.c -e build/CMakeFiles/3.2.2/CompilerIdCXX/CMakeCXXCompilerId.cpp -e build/CMakeFiles/3.2.2/CompilerIdC/CMakeCCompilerId.c -e test -e pd -e thread --gcov-options '\-lp'
        - sudo apt-get install --yes doxygen graphviz
        - rm -rf doc
        - mkdir -p doc
        - git clone -b gh-pages git@github.com:pierreguillot/zpd.git --single-branch doc
        - cd doc
        - git rm -rf .
        - cd ../xpd
        - doxygen xpddoc
        - cd ../cpd
        - doxygen cpddoc
        - cd ../
        - cp config/doxygen.css doc/doxygen.css
        - cp config/index.html doc/index.html
        - cd doc/
        - git add .
        - git commit -m "Automated documentation build for changeset git rev-parse --verify HEAD."
        - git push origin gh-pages
        - cd ../
      env:
        - Coveralls and Documentations

    - os: linux
      compiler: gcc
      env:
        - ZPD_ARCH=64bit

    - os: linux
      compiler: gcc
      env:
        - ZPD_ARCH=32bit

    - os: linux
      compiler: clang
      env:
        - ZPD_ARCH=64bit

    - os: linux
      compiler: clang
      env:
        - ZPD_ARCH=32bit

    - os: osx
      compiler: gcc
      env:
        - ZPD_ARCH=i386_x86_64

    - os: osx
      compiler: clang
      env:
        - ZPD_ARCH=i386_x86_64

script:
  - mkdir build && cd build
  - cmake .. -DARCH=$ZPD_ARCH
  - cmake --build .
  - cd ../
  - ./build/test

after_success:
  - mkdir zpd
  - cp lib zpd/lib
  - cp cpd zpd/cpd
  - cp xpd zpd/xpd
  - cp README.md zpd/readme.txt
  - cp LICENSE zpd/license.txt
  - zip -r zpd_$TRAVIS_OS_NAME_$ZPD_ARCH_$TRAVIS_TAG.zip zpd

deploy:
  provider: releases
  api_key:
    secure: M15LaLK5eBXRZtiK3NgxNxTJMdHxhrtjKW3qbjVCUhvR6OiHBlhQaRD2D6be0ZYcr3ZFf4zHIXnSj/ntIGh889eOoovvGG2mWqC5DyMrDg7YtPmXoyYchwZmhv6RC6kScDNNBwVZM9aAoVAZKBrlqlcbXrSWTb1EszYuTC7egWZhDIM6HhShSX2P/jefyKgRDVwUcupdgEgo1FMT6klnUd5XkUOMVzOpaRwP2SEMzt8Sx0EjaqTL7mbL+HbGAXp97fFhzpKxzyfiG4ntjUKI4vGsqlXLQQJbgoxoavab610PxxNk7l8QpEY2/Lz1QwuU8vwn7nejv0oA75Jkc4WBIAJ1rTy1DsyUYaycy2eMG9ci0aUEZmqyTJtBzefgf/KK8gh6GcBzDMdr5Ol9NvyXRj1RV09//7jzg04YX+GY4UVuvhlzk2PXL8PtVj6EKptZw30WeArcLNECJVl884w6r0sTX7Z57xH90oOycvLzrnxCZeuXKw0QNoTb1mcjiPqBtSF42rGs8nlaS4nPvbLmJHkqgiCo8D6stcO6HeAtAz34NbFgYzf7HCLul9CKjweesHP28I1xsNbtBnDGUwRaLKi2g79UzlL/LKLlLjKLaoNFqaJVFj41KJy6U6Gk7PvUM+k+vwnIslpqIhwwvEu15esNFtfRrvR7/LjniBxpIdY=
  file: zpd_$TRAVIS_OS_NAME_$ZPD_ARCH_$TRAVIS_TAG.zip
  on:
    tags: true
    repo: pierreguillot/zpd
    branch: master
