language: c
dist: trusty
sudo: required

notifications:
  email: false

git:
  submodules: true
  depth: 3
  
install:
  - wget -qO- http://www.cmake.org/files/v3.1/cmake-3.1.0-Linux-x86_64.tar.gz | tar xvz

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages: ['python-pip', 'python-yaml']
      before_script:
        - pip install --user git+git://github.com/eddyxu/cpp-coveralls.git
      script:
          - mkdir build && cd build
          - cmake -DCOVERALLS=1 -DCMAKE_BUILD_TYPE=Debug ..
          - cmake --build .
          - cd ../
          - ./build/zpdtest pwd

      after_success:
        - coveralls -e build/CMakeFiles/feature_tests.cxx -e build/CMakeFiles/feature_tests.c -e build/CMakeFiles/CompilerIdCXX/CMakeCXXCompilerId.cpp -e build/CMakeFiles/CompilerIdCXX/CMakeCXXCompilerId.c -e build/CMakeFiles/3.2.2/CompilerIdCXX/CMakeCXXCompilerId.cpp -e build/CMakeFiles/3.2.2/CompilerIdC/CMakeCCompilerId.c -e test -e pd --gcov-options '\-lp'
        - sudo apt-get install --yes doxygen graphviz
        - rm -rf doc
        - mkdir -p doc
        - openssl aes-256-cbc
          -K $encrypted_e84e7849f94f_key
          -iv $encrypted_e84e7849f94f_iv
          -in travisci_rsa.enc
          -out config/travisci_rsa
          -d
        - chmod 0600 config/travisci_rsa
        - cp config/travisci_rsa ~/.ssh/id_rsa
        - git clone -b gh-pages git@github.com:pierreguillot/zpd.git --single-branch doc
        - cd doc
        - git rm -rf .
        - cd ../
        - doxygen zpddoc
        - cd doc
        - git add .
        - git commit -m "Automated documentation build for changeset git rev-parse --verify HEAD."
        - git push origin gh-pages
        - cd ../
      env:
        - Coveralls and Documentations

    - os: linux
      compiler: gcc
      script:
        - mkdir build && cd build
        - cmake ..
        - cmake --build .
        - cd ../
        - ./build/zpdtest pwd
      env:
        - Libs and Tests

    - os: linux
      compiler: clang
      script:
        - mkdir build && cd build
        - cmake ..
        - cmake --build .
        - cd ../
        - ./build/zpdtest pwd
      env:
        - Libs and Tests

    - os: osx
      compiler: gcc
      script:
        - mkdir build && cd build
        - cmake ..
        - cmake --build .
        - cd ../
        - ./build/zpdtest pwd
      env:
        - Libs and Tests

    - os: osx
      compiler: clang
      script:
        - mkdir build && cd build
        - cmake ..
        - cmake --build .
        - cd ../
        - ./build/zpdtest pwd
      env:
        - Libs and Tests
