language: c

notifications:
  email: false

git:
  submodules: true
  depth: 3

matrix:
  include:
    - os: linux
      compiler: gcc
      before_script:
        - pip install --user git+git://github.com/eddyxu/cpp-coveralls.git
      script:
          - mkdir build && cd build
          - cmake -DCOVERALLS=1 ..
          - cmake --build .
          - cd ../
          - ./test/zpdtest pwd
      after_success:
        - coveralls --exclude lib --exclude test --gcov-options '\-lp' --gcov 'gcov-4.9'

    - os: linux
      compiler: clang
      script:
        - mkdir build && cd build
        - cmake ..
        - cmake --build .
        - cd ../
        - ./test/zpdtest pwd

    - os: osx
      compiler: gcc
      script:
        - mkdir build && cd build
        - cmake ..
        - cmake --build .
        - cd ../
        - ./test/zpdtest pwd

    - os: osx
      compiler: clang
      script:
        - mkdir build && cd build
        - cmake ..
        - cmake --build .
        - cd ../
        - ./test/zpdtest pwd
