language: c

notifications:
  email: false

git:
  submodules: true
  depth: 5

compiler:
  - clang
  - gcc
os:
  - linux
  - osx

script:
  - mkdir build && cd build
  - cmake ..
  - cmake --build .
  - ./test/zpdtest pwd
