
environment:
   matrix:
      - CONFIGURATION: Debug
        PLATFORM: Win32
        ZIP: zpd_win_32
      - CONFIGURATION: Debug
        PLATFORM: x64
        ZIP: zpd_win_64

os: Visual Studio 2015

install:
    - git submodule update --init --recursive

build_script:
    - mkdir build
    - cd build
    - cmake .. -G "Visual Studio 14 2015"
    - cmake --build .

after_build:
    - cd %APPVEYOR_BUILD_FOLDER%
    - mkdir zpd
    - xcopy /E %APPVEYOR_BUILD_FOLDER%\lib\* %APPVEYOR_BUILD_FOLDER%\zpd\lib\*
    - xcopy /E %APPVEYOR_BUILD_FOLDER%\cpd\* %APPVEYOR_BUILD_FOLDER%\zpd\cpd\*
    - xcopy /E %APPVEYOR_BUILD_FOLDER%\xpd\* %APPVEYOR_BUILD_FOLDER%\zpd\xpd\*
    - copy %APPVEYOR_BUILD_FOLDER%\README.md %APPVEYOR_BUILD_FOLDER%\zpd\readme.txt
    - copy %APPVEYOR_BUILD_FOLDER%\LICENSE.txt %APPVEYOR_BUILD_FOLDER%\zpd\license.txt
    - del /F /S /Q /A %APPVEYOR_BUILD_FOLDER%\zpd\lib\*.exp
    - del /F /S /Q /A %APPVEYOR_BUILD_FOLDER%\zpd\lib\test.lib
    - 7z a %ZIP%.zip %APPVEYOR_BUILD_FOLDER%\zpd\

test_script:
    - cd %APPVEYOR_BUILD_FOLDER%\build
    - test.exe

artifacts:
  - path: '*.zip'

deploy:
  provider: GitHub
  auth_token:
    secure: iE/hKkl+fIBulDvgwV9AMMrmGuyIyVCrCp7Nb0AXVMglxUds7pg450AV61gmVcUE
  artifact: /.*\.zip/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true

#---------------------------------#
#         notifications           #
#---------------------------------#
notifications:

  # Email
  - provider: Email
    on_build_status_changed: false
