
environment:
   matrix:
      - CONFIGURATION: Debug
        PLATFORM: Win32
      - CONFIGURATION: Debug
        PLATFORM: x64
      - CONFIGURATION: Release
        PLATFORM: Win32
      - CONFIGURATION: Release
        PLATFORM: x64

os: Visual Studio 2015

install:
    - git submodule update --init --recursive
    - git clone -q --branch=master https://github.com/pierreguillot/pthread.git C:\projects\zpd\pthread
    - cd pthread\lib\x86
    - dir /s /b /o:gn
    - cd ..\..\..\

build_script:
    - mkdir build
    - cd build
    - cmake .. -G "Visual Studio 14 2015"
    - cmake --build .

#---------------------------------#
#         notifications           #
#---------------------------------#
notifications:

  # Email
  - provider: Email
    on_build_status_changed: false
